apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rancher-demo
  namespace: default
spec:
  rules:
  - host: rancher-demo.18.194.29.61.xip.io
    http:
      paths:
      - backend:
          serviceName: rancher-demo
          servicePort: 80
        path: /